export const ACTION_STRING = {
  authLogin: "AUTH_LOGIN",
  authLogout: "AUTH_LOGOUT",
  authRegister: "AUTH_REGISTER",
  pending: "_PENDING",
  fulfilled: "_FULFILLED",
  rejected: "_REJECTED",
  getProducts: "GET_PRODUCTS",
  createProduct: "CREATE_PRODUCT",
  updateProducts: "UPDATE_PRODUCT",
  getDetailProduct: "GET_PRODUCT_DETAIL",
  getProfile: "GET_PROFILE",
  updateProfile: "UPDATE_PROFILE",
  getPromos: "GET_PROMOS",
  resetProfile: "RESET_PROFILE",
  resetTransaction: "RESET_TRANSACTIONS",
  addToCart: "ADD_TO_CART",
};
